[package]
name = "port_sniffer"
version = "0.1.0"
authors = ["F4zii <fazbosoreq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
